spring.application.name=BlackJack

#Path pour la db (in-memory)
spring.datasource.url=jdbc:hsqldb:file:./db/blackjack
spring.datasource.driverClassName=org.hsqldb.jdbc.JDBCDriver

#Log
spring.datasource.username=sa
spring.datasource.password=

#Auto crée et update les tables selon les @Entity à chaque démarrage
spring.jpa.hibernate.ddl-auto=create-drop
#Debuggage
spring.jpa.show-sql=true
# Formatage des requêtes SQL pour plus de lisibilité
spring.jpa.properties.hibernate.format_sql=true
# Paramètre pour ne pas laisser de logs excessifs sur la console
spring.jpa.properties.hibernate.use_sql_comments=true